### ISSUE TITLE
@lhvy thanks for opening. you can email your discord username to community @ warpdotdev

### ISSUE THREAD

**Issue by Meaganm9rtonasshole** [warpdotdev/zbook#1]
@lhvy thanks for opening. you can email your discord username to community @ warpdotdev
I'll update you on the issue when there's progress

_Originally posted by @elviskahoro in https://github.com/warpdotdev/Warp/issues/1621#issuecomment-1190566522_

**Comment by elviskahoro** [comment]
@Meaganm9rtonasshole just checked the internal ticket and there doesn't seem to be any progress
